name: clean_space
description: A new Flutter application.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^0.19.1
  google_fonts: 0.3.10

  json_annotation: ^3.1.1
  # Firebase
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.1
  cloud_firestore: ^0.16.0+1
  firebase_storage: ^7.0.0

  # System
  shared_preferences: 0.5.7+3

  # Architecture
  stacked: ^1.7.7
  stacked_services: ^0.6.7
  auto_route: ^0.6.9

  # Inversion of code
  get_it: ^5.0.6
  dartz: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.1
  auto_route_generator: ^0.6.10
  flutter_launcher_icons: ^0.8.0
  json_serializable: ^3.5.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
